name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohttp
  - astropy
  - async-timeout
  - autopep8
  - bokeh
  - cffi
  - click
  - coverage
  - cython
  - dask
  - datashader
  - distributed
  - flake8
  - holoviews
  - imageio
  - imagesize
  - ipython
  - isort
  - lz4
  - matplotlib
  - mypy
  - networkx
  - numpy
  - pandas
  - pillow
  - pip
  - psutil
  - psycopg2
  - pyarrow
  - pycodestyle
  - pyflakes
  - pygments
  - pylint
  - pytest
  - pytest-cov
  - python==3.7.1
  - python-graphviz
  - pyyaml
  - pyzmq
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sep
  - sqlalchemy
  - sqlite
  - tornado
  - transaction
  - xarray
  - xlrd
  - pip:
    - better-exceptions
    - bumpversion
    - dask-image
    - docker
    - msgpack
    - sphinx-autodoc-typehints
    - voluptuous
    - jupyterhub
    - jupyterlab
    - photutils
    - sphinx
